name: Pulumi CI/CD Pipeline

on:
  push:
    branches:
      - main  # O pipeline será acionado sempre que houver um push na branch main
  pull_request:
    branches:
      - main  # O pipeline também pode ser acionado por pull requests para a branch main

jobs:
  test:
    runs-on: ubuntu-latest  # Escolha o ambiente de execução (Ubuntu é comum)

    steps:
      # 1. Checkout do código
      - name: Checkout repository
        uses: actions/checkout@v2

      # 2. Configurar Python
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'  # Altere para a versão do Python que você está usando

      # 3. Instalar dependências do projeto
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt  # Certifique-se de ter o arquivo requirements.txt no seu repositório

      # 4. Configurar Pulumi
      - name: Set up Pulumi
        uses: pulumi/action@v3
        with:
          pulumi_version: 'latest'  # Escolha a versão do Pulumi que deseja usar

      # 5. Rodar os testes da infraestrutura
      - name: Run infrastructure tests
        run: |
          pulumi stack select <your-stack-name>  # Substitua pelo nome do seu stack
          pytest test_infra.py  # Execute os testes com o pytest
