name: Pulumi CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout do código
      - name: Checkout repository
        uses: actions/checkout@v2

      # 2. Configurar Python
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      # 3. Instalar dependências do projeto
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Create Pulumi Stack
        run: pulumi stack init dev

      # 5. Rodar os testes da infraestrutura
      - name: Run infrastructure tests
        run: |
          pulumi stack select dev  # Substitua pelo nome do seu stack
          pytest test_infra.py  # Execute os testes com o pytest
